name: 'CI -> Pipeline'

on:
    pull_request:
        branches: [stable]
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: 'Lint'
        runs-on: ubuntu-24.04
        permissions: write-all
        steps:
            - name: 'Checkout'
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  persist-credentials: false

            - name: 'Setup Bun'
              uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

            - name: 'Setup dependencies'
              run: bun install --frozen-lockfile

            - name: 'Run lint'
              run: bun run lint
